#!/bin/dash

# dwhy by www.ramoncasares.com 2011
# License: GPL

if test "[$1]" = "[]" ; then
   echo "Enter: dwhy filename"
   echo "       to let Debian explain why filename is in your system"
   return 1
fi

if test -e "$1" ; then
   TARGET="$(readlink -f "$1")"
   if test -L "$1" ; then
      echo "$1 -> $TARGET"
   fi
else
   FIRSTTARGET="$(which "$1")"
   TARGET="$(readlink -f "$FIRSTTARGET")"
   if test -L "$FIRSTTARGET" ; then
      echo "$1 -> $FIRSTTARGET -> $TARGET"
   else
      if test "[$TARGET]" = "[]" ; then
         PACKAGES=$1
      else
         echo "$1 -> $TARGET"
      fi
   fi
fi

if test "[$TARGET]" = "[]" ; then
   echo "$1: file not found, try as package"
else
   file "$TARGET"
fi

if test "[$PACKAGES]" = "[]" ; then
   PACKAGES=$(dpkg-query --search "$TARGET" | cut -d: -f1 | sed s/,//g)
fi

if test "[$PACKAGES]" = "[]" ; then
   echo "$TARGET is not in a Debian package"
else
 for PACKAGE in $PACKAGES ; do
   DFILE=$(apt-cache show "$PACKAGE" | grep "^Filename: " | cut -d' ' -f2)
   PRIORITY=$(dpkg-query -W -f='${Priority}' $PACKAGE)
   echo "Package: $DFILE [$PRIORITY]"
   dtree $PACKAGE
 done
fi

exit 0

